apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels: 
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: docker.io/busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: init-myservice
    image: docker.io/busybox
    command: ['sh', '-c', 'echo init-service && sleep 2']
  - name: init-mydb
    image: docker.io/busybox
    command: ['sh', '-c', 'echo init-mydb && sleep 2']
