apiVersion: v1
kind: Service
metadata:
  name: es-service
spec:
  selector:
    app: ccb-es6
  ports:
  - protocol: TCP
    name: http
    port: 9200
    targetPort: 9200
  - protocol: TCP
    name: tcp
    port: 9300
    targetPort: 9300
