apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2018-07-24T08:35:08Z
  generateName: tomcat-858b8c476d-
  labels:
    app: tomcat
    node: devops-102
    pod-template-hash: "4146470328"
  name: tomcat-858b8c476d-vnm98
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: tomcat-858b8c476d
    uid: 78daa97d-8f1c-11e8-82cd-080027b7c4e9
  resourceVersion: "27194"
  selfLink: /api/v1/namespaces/default/pods/tomcat-858b8c476d-vnm98
  uid: 78e6d785-8f1c-11e8-82cd-080027b7c4e9
spec:
  containers:
  - image: docker.io/tomcat
    imagePullPolicy: Always
    name: tomcat
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-trvqv
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: devops-102
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-trvqv
    secret:
      defaultMode: 420
      secretName: default-token-trvqv
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-07-24T08:35:08Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-07-24T08:35:38Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2018-07-24T08:35:08Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://9f3aa2d3d6c1937d4209a44820c1cd06f7eaf8796848c759e19410358aea4866
    image: docker.io/tomcat:latest
    imageID: docker-pullable://docker.io/tomcat@sha256:87ad70ceaafd5c71301b081b37ca2795bd6c7c1a5599a8c92c9447bbd225ae47
    lastState: {}
    name: tomcat
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-07-24T08:35:37Z
  hostIP: 192.168.0.102
  phase: Running
  podIP: 10.244.2.6
  qosClass: BestEffort
  startTime: 2018-07-24T08:35:08Z
